name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-linux-musl, i686-linux-musl, powerpc64le-linux-musl, arm-linux-musleabihf, aarch64-linux-musl]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag image:${{ matrix.target }} --build-arg TARGET=${{ matrix.target }} --target deploy
      env:
        DOCKER_BUILDKIT: 1

    - name: Test Docker Image
      run: docker run --rm -t image:${{ matrix.target }}

    - name: Push Docker Image
      run: echo "$DOCKERHUB_TOKEN" | docker login --username horseshoe --password-stdin && docker push image:${{ matrix.target }}
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
